# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/HP/Desktop/Sem 7/Seminar/Updated DIW FPGA/Updated DIW FPGA.srcs/sources_1/ip/FP_SUB/FP_SUB.xci
# IP: The module: 'FP_SUB' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/Desktop/Sem 7/Seminar/Updated DIW FPGA/Updated DIW FPGA.gen/sources_1/ip/FP_SUB/FP_SUB_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_SUB'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/HP/Desktop/Sem 7/Seminar/Updated DIW FPGA/Updated DIW FPGA.srcs/sources_1/ip/FP_SUB/FP_SUB.xci
# IP: The module: 'FP_SUB' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/Desktop/Sem 7/Seminar/Updated DIW FPGA/Updated DIW FPGA.gen/sources_1/ip/FP_SUB/FP_SUB_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_SUB'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
