@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Oct 12 00:04:23 +0530 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Eight_x_Eight_DCT_tb_behav -key {Behavioral:sim_1:Functional:Eight_x_Eight_DCT_tb} -tclbatch Eight_x_Eight_DCT_tb.tcl -view C:/Users/HP/Desktop/Sem 7/Seminar/Updated DIW FPGA/EightBitDCT_tb_behav.wcfg -log simulate.log"
call xsim  Eight_x_Eight_DCT_tb_behav -key {Behavioral:sim_1:Functional:Eight_x_Eight_DCT_tb} -tclbatch Eight_x_Eight_DCT_tb.tcl -view C:/Users/HP/Desktop/Sem 7/Seminar/Updated DIW FPGA/EightBitDCT_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
